### ISSUE TITLE
Differentiate "yes" & "maybe" participants in the list of attendants

### ISSUE THREAD

**Issue by lukasbeck** [dragbone/slacking-pizzabot#3]
Currently, the pizzabot simply lists all participants with no way to tell whether that person voted *yes* or only *maybe*. I would be helpful to be able to differentiate these two types, e.g. by putting attendants with maybe-votes in parentheses:

     Participants: John, (Richard), Sally

**Comment by dragbone** [comment]
Fixed in 9145ac334682ebb437a6065b181eacd65f123714
